### PR TITLE
hostname -I

### PR DESCRIPTION
**Pull request by Sascha-1**
Simpler?

### CODE REVIEW

**Review by willief — CHANGES_REQUESTED** [review]
this is cleaner
hostname -i  (lowercase) would give us only the first ip addr  -I gives them all if several are set.

LOCAL_IP=$(hostname -i)

**Review by willief — COMMENTED** [review]
yes thats cleaner

**Comment by Sascha-1** [comment]
If connected to a VPN, hostname -I gives three values, so cutting column 1 may still be a good idea. Not sure what the other columns are.

**Comment by willief** [comment]
@Sascha-1  "If connected to a VPN, hostname -I gives three values, so cutting column 1 may still be a good idea. Not sure what the other columns are."

I have no VPN setup. Please paste the output of `hostname -I `
Still think `hostname -i `   <-note lowercase                               would be simpler. Can you paste the output of that on you VPN as well please?

**Comment by Sascha-1** [comment]
Without VPN:

```
sascha@sascha-Librem-15-v3:~$ hostname -i
127.0.1.1
sascha@sascha-Librem-15-v3:~$ hostname -I
192.168.8.100 
```

With ProtonVPN:
```
sascha@sascha-Librem-15-v3:~$ hostname -i
127.0.1.1
sascha@sascha-Librem-15-v3:~$ hostname -I
192.168.8.100 10.28.0.3 fdeb:446c:912d:8da:: 
```

**Comment by willief** [comment]
hostname -i is too fragile

We are safer with the long form two lines 
```
ACTIVE_IF=$( ( cd /sys/class/net || exit; echo *)|awk '{print $1;}')
LOCAL_IP=$(ifdata -pa "$ACTIVE_IF")
```

**Pull request closed without merging**
